// Gina 学英语 - API 端点
// 兼容 Cloudflare Pages Functions 和 Vercel Edge Functions

// 词库数据（构建时注入）
const WORD_DATA = [
  {
    "word": "zoo",
    "phonetic": "/zuː/",
    "pos": "n.",
    "meaning": "动物园",
    "example": "We go to the zoo.",
    "unit": "Unit 1 At the Zoo",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/20818204/pexels-photo-20818204.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Pexels User",
    "id": "grade2_0001",
    "type": "noun"
  },
  {
    "word": "elephant",
    "phonetic": "/ˈelɪfənt/",
    "pos": "n.",
    "meaning": "大象",
    "example": "The elephant is big.",
    "unit": "Unit 1 At the Zoo",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/25754094/pexels-photo-25754094.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Lloyd Douglas",
    "id": "grade2_0002",
    "type": "noun"
  },
  {
    "word": "monkey",
    "phonetic": "/ˈmʌŋki/",
    "pos": "n.",
    "meaning": "猴子",
    "example": "The monkey is small.",
    "unit": "Unit 1 At the Zoo",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/32860812/pexels-photo-32860812.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Hobi Photography",
    "id": "grade2_0003",
    "type": "noun"
  },
  {
    "word": "tiger",
    "phonetic": "/ˈtaɪɡə(r)/",
    "pos": "n.",
    "meaning": "老虎",
    "example": "The tiger is strong.",
    "unit": "Unit 1 At the Zoo",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/18150604/pexels-photo-18150604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Thang Cao",
    "id": "grade2_0004",
    "type": "noun"
  },
  {
    "word": "lion",
    "phonetic": "/ˈlaɪən/",
    "pos": "n.",
    "meaning": "狮子",
    "example": "The lion is tall.",
    "unit": "Unit 1 At the Zoo",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/32420367/pexels-photo-32420367.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Magda Ehlers",
    "id": "grade2_0005",
    "type": "noun"
  },
  {
    "word": "bird",
    "phonetic": "/bɜːd/",
    "pos": "n.",
    "meaning": "鸟",
    "example": "The bird can fly.",
    "unit": "Unit 1 At the Zoo",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/29275539/pexels-photo-29275539.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Enrique Hidalgo",
    "id": "grade2_0006",
    "type": "noun"
  },
  {
    "word": "cat",
    "phonetic": "/kæt/",
    "pos": "n.",
    "meaning": "猫",
    "example": "The cat is cute.",
    "unit": "Unit 1 At the Zoo",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/30002394/pexels-photo-30002394.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Helena Jankovičová Kováčová",
    "id": "grade2_0007",
    "type": "noun"
  },
  {
    "word": "dog",
    "phonetic": "/dɒɡ/",
    "pos": "n.",
    "meaning": "狗",
    "example": "The dog is friendly.",
    "unit": "Unit 1 At the Zoo",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/27107874/pexels-photo-27107874.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Chirag Captures",
    "id": "grade2_0008",
    "type": "noun"
  },
  {
    "word": "food",
    "phonetic": "/fuːd/",
    "pos": "n.",
    "meaning": "食物",
    "example": "I like food.",
    "unit": "Unit 2 My Favourite Food",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/36501108/pexels-photo-36501108.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Wallace  Castro",
    "id": "grade2_0009",
    "type": "noun"
  },
  {
    "word": "rice",
    "phonetic": "/raɪs/",
    "pos": "n.",
    "meaning": "米饭",
    "example": "I eat rice.",
    "unit": "Unit 2 My Favourite Food",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/17563535/pexels-photo-17563535.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Jubair Bin Iqbal",
    "id": "grade2_0010",
    "type": "noun"
  },
  {
    "word": "noodles",
    "phonetic": "/ˈnuːdlz/",
    "pos": "n.",
    "meaning": "面条",
    "example": "I like noodles.",
    "unit": "Unit 2 My Favourite Food",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/29792753/pexels-photo-29792753.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Abdulkadir Emiroğlu",
    "id": "grade2_0011",
    "type": "noun"
  },
  {
    "word": "fish",
    "phonetic": "/fɪʃ/",
    "pos": "n.",
    "meaning": "鱼",
    "example": "The fish is yummy.",
    "unit": "Unit 2 My Favourite Food",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/27322157/pexels-photo-27322157.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "gül aksoy",
    "id": "grade2_0012",
    "type": "noun"
  },
  {
    "word": "meat",
    "phonetic": "/miːt/",
    "pos": "n.",
    "meaning": "肉",
    "example": "I eat meat.",
    "unit": "Unit 2 My Favourite Food",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/8444102/pexels-photo-8444102.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Rickie-Tom Schünemann",
    "id": "grade2_0013",
    "type": "noun"
  },
  {
    "word": "egg",
    "phonetic": "/eɡ/",
    "pos": "n.",
    "meaning": "鸡蛋",
    "example": "I have an egg.",
    "unit": "Unit 2 My Favourite Food",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/32149473/pexels-photo-32149473.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Christopher Welsch Leveroni",
    "id": "grade2_0014",
    "type": "noun"
  },
  {
    "word": "milk",
    "phonetic": "/mɪlk/",
    "pos": "n.",
    "meaning": "牛奶",
    "example": "I drink milk.",
    "unit": "Unit 2 My Favourite Food",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/4121867/pexels-photo-4121867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Olena Bohovyk",
    "id": "grade2_0015",
    "type": "noun"
  },
  {
    "word": "bread",
    "phonetic": "/bred/",
    "pos": "n.",
    "meaning": "面包",
    "example": "I eat bread.",
    "unit": "Unit 2 My Favourite Food",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/32611701/pexels-photo-32611701.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nguyen Ngoc Tien",
    "id": "grade2_0016",
    "type": "noun"
  },
  {
    "word": "school",
    "phonetic": "/skuːl/",
    "pos": "n.",
    "meaning": "学校",
    "example": "I go to school.",
    "unit": "Unit 3 My School",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/8500416/pexels-photo-8500416.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "RDNE Stock project",
    "id": "grade2_0017",
    "type": "noun"
  },
  {
    "word": "classroom",
    "phonetic": "/ˈklɑːsruːm/",
    "pos": "n.",
    "meaning": "教室",
    "example": "This is my classroom.",
    "unit": "Unit 3 My School",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/8500643/pexels-photo-8500643.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "RDNE Stock project",
    "id": "grade2_0018",
    "type": "noun"
  },
  {
    "word": "teacher",
    "phonetic": "/ˈtiːtʃə(r)/",
    "pos": "n.",
    "meaning": "老师",
    "example": "The teacher is kind.",
    "unit": "Unit 3 My School",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/5212675/pexels-photo-5212675.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Max Fischer",
    "id": "grade2_0019",
    "type": "noun"
  },
  {
    "word": "friend",
    "phonetic": "/frend/",
    "pos": "n.",
    "meaning": "朋友",
    "example": "My friend is nice.",
    "unit": "Unit 3 My School",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/5506093/pexels-photo-5506093.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Maksim Goncharenok",
    "id": "grade2_0020",
    "type": "noun"
  },
  {
    "word": "book",
    "phonetic": "/bʊk/",
    "pos": "n.",
    "meaning": "书",
    "example": "I read a book.",
    "unit": "Unit 3 My School",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/415071/pexels-photo-415071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Pixabay",
    "id": "grade2_0021",
    "type": "noun"
  },
  {
    "word": "pen",
    "phonetic": "/pen/",
    "pos": "n.",
    "meaning": "钢笔",
    "example": "I have a pen.",
    "unit": "Unit 3 My School",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/7153019/pexels-photo-7153019.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mathias Reding",
    "id": "grade2_0022",
    "type": "noun"
  },
  {
    "word": "bag",
    "phonetic": "/bæɡ/",
    "pos": "n.",
    "meaning": "书包",
    "example": "My bag is new.",
    "unit": "Unit 3 My School",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/33235378/pexels-photo-33235378.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "oPorto",
    "id": "grade2_0023",
    "type": "noun"
  },
  {
    "word": "desk",
    "phonetic": "/desk/",
    "pos": "n.",
    "meaning": "课桌",
    "example": "I sit at the desk.",
    "unit": "Unit 3 My School",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/8004023/pexels-photo-8004023.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Darina Belonogova",
    "id": "grade2_0024",
    "type": "noun"
  },
  {
    "word": "play",
    "phonetic": "/pleɪ/",
    "pos": "v.",
    "meaning": "玩",
    "example": "Let's play together.",
    "unit": "Unit 4 Let's Play",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/33327422/pexels-photo-33327422.png?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "BI ravencrow",
    "id": "grade2_0025",
    "type": "verb"
  },
  {
    "word": "ball",
    "phonetic": "/bɔːl/",
    "pos": "n.",
    "meaning": "球",
    "example": "I have a ball.",
    "unit": "Unit 4 Let's Play",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/11415807/pexels-photo-11415807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tamhasip Khan",
    "id": "grade2_0026",
    "type": "noun"
  },
  {
    "word": "kite",
    "phonetic": "/kaɪt/",
    "pos": "n.",
    "meaning": "风筝",
    "example": "I fly a kite.",
    "unit": "Unit 4 Let's Play",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/35098545/pexels-photo-35098545.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ty Nguyễn",
    "id": "grade2_0027",
    "type": "noun"
  },
  {
    "word": "run",
    "phonetic": "/rʌn/",
    "pos": "v.",
    "meaning": "跑",
    "example": "I can run fast.",
    "unit": "Unit 4 Let's Play",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/11757388/pexels-photo-11757388.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mohammed Abubakr",
    "id": "grade2_0028",
    "type": "verb"
  },
  {
    "word": "jump",
    "phonetic": "/dʒʌmp/",
    "pos": "v.",
    "meaning": "跳",
    "example": "I can jump high.",
    "unit": "Unit 4 Let's Play",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/5214079/pexels-photo-5214079.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "VV 97",
    "id": "grade2_0029",
    "type": "verb"
  },
  {
    "word": "sing",
    "phonetic": "/sɪŋ/",
    "pos": "v.",
    "meaning": "唱",
    "example": "I like to sing.",
    "unit": "Unit 4 Let's Play",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/7503362/pexels-photo-7503362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "RDNE Stock project",
    "id": "grade2_0030",
    "type": "verb"
  },
  {
    "word": "dance",
    "phonetic": "/dɑːns/",
    "pos": "v.",
    "meaning": "跳舞",
    "example": "I can dance.",
    "unit": "Unit 4 Let's Play",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/29046700/pexels-photo-29046700.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Israyosoy S.",
    "id": "grade2_0031",
    "type": "verb"
  },
  {
    "word": "happy",
    "phonetic": "/ˈhæpi/",
    "pos": "adj.",
    "meaning": "开心的",
    "example": "I am happy.",
    "unit": "Unit 4 Let's Play",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/31682443/pexels-photo-31682443.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Alexas Fotos",
    "id": "grade2_0032",
    "type": "adjective"
  },
  {
    "word": "family",
    "phonetic": "/ˈfæməli/",
    "pos": "n.",
    "meaning": "家庭",
    "example": "I love my family.",
    "unit": "Unit 5 My Family",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/34928343/pexels-photo-34928343.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "bigmass media and printing",
    "id": "grade2_0033",
    "type": "noun"
  },
  {
    "word": "father",
    "phonetic": "/ˈfɑːðə(r)/",
    "pos": "n.",
    "meaning": "爸爸",
    "example": "My father is tall.",
    "unit": "Unit 5 My Family",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/4609047/pexels-photo-4609047.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Vlada Karpovich",
    "id": "grade2_0034",
    "type": "noun"
  },
  {
    "word": "mother",
    "phonetic": "/ˈmʌðə(r)/",
    "pos": "n.",
    "meaning": "妈妈",
    "example": "My mother is kind.",
    "unit": "Unit 5 My Family",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/30225583/pexels-photo-30225583.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Asad Photo Maldives",
    "id": "grade2_0035",
    "type": "noun"
  },
  {
    "word": "brother",
    "phonetic": "/ˈbrʌðə(r)/",
    "pos": "n.",
    "meaning": "哥哥/弟弟",
    "example": "My brother is fun.",
    "unit": "Unit 5 My Family",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/14195784/pexels-photo-14195784.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "rehman yousaf",
    "id": "grade2_0036",
    "type": "noun"
  },
  {
    "word": "sister",
    "phonetic": "/ˈsɪstə(r)/",
    "pos": "n.",
    "meaning": "姐姐/妹妹",
    "example": "My sister is nice.",
    "unit": "Unit 5 My Family",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/12789183/pexels-photo-12789183.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "VIKTOR KONDRATIUK",
    "id": "grade2_0037",
    "type": "noun"
  },
  {
    "word": "baby",
    "phonetic": "/ˈbeɪbi/",
    "pos": "n.",
    "meaning": "宝宝",
    "example": "The baby is cute.",
    "unit": "Unit 5 My Family",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/10864087/pexels-photo-10864087.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mikhail Konetski",
    "id": "grade2_0038",
    "type": "noun"
  },
  {
    "word": "grandpa",
    "phonetic": "/ˈɡrænpɑː/",
    "pos": "n.",
    "meaning": "爷爷/外公",
    "example": "My grandpa is old.",
    "unit": "Unit 5 My Family",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/7118191/pexels-photo-7118191.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "cottonbro studio",
    "id": "grade2_0039",
    "type": "noun"
  },
  {
    "word": "grandma",
    "phonetic": "/ˈɡrænmɑː/",
    "pos": "n.",
    "meaning": "奶奶/外婆",
    "example": "My grandma is kind.",
    "unit": "Unit 5 My Family",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/9385076/pexels-photo-9385076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Анастасия Триббиани",
    "id": "grade2_0040",
    "type": "noun"
  },
  {
    "word": "day",
    "phonetic": "/deɪ/",
    "pos": "n.",
    "meaning": "天",
    "example": "It is a good day.",
    "unit": "Unit 6 My Day",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/27901404/pexels-photo-27901404.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tom Swinnen",
    "id": "grade2_0041",
    "type": "noun"
  },
  {
    "word": "morning",
    "phonetic": "/ˈmɔːnɪŋ/",
    "pos": "n.",
    "meaning": "早上",
    "example": "Good morning!",
    "unit": "Unit 6 My Day",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/29561591/pexels-photo-29561591.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Lauma Augstkalne",
    "id": "grade2_0042",
    "type": "noun"
  },
  {
    "word": "afternoon",
    "phonetic": "/ˌɑːftəˈnuːn/",
    "pos": "n.",
    "meaning": "下午",
    "example": "Good afternoon!",
    "unit": "Unit 6 My Day",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/30562548/pexels-photo-30562548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Brin Silver",
    "id": "grade2_0043",
    "type": "noun"
  },
  {
    "word": "eat",
    "phonetic": "/iːt/",
    "pos": "v.",
    "meaning": "吃",
    "example": "I eat breakfast.",
    "unit": "Unit 6 My Day",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/10875381/pexels-photo-10875381.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Wolf  Art",
    "id": "grade2_0044",
    "type": "verb"
  },
  {
    "word": "sleep",
    "phonetic": "/sliːp/",
    "pos": "v.",
    "meaning": "睡觉",
    "example": "I sleep at night.",
    "unit": "Unit 6 My Day",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/7641345/pexels-photo-7641345.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "MART  PRODUCTION",
    "id": "grade2_0045",
    "type": "verb"
  },
  {
    "word": "play",
    "phonetic": "/pleɪ/",
    "pos": "v.",
    "meaning": "玩",
    "example": "I play games.",
    "unit": "Unit 6 My Day",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/33327422/pexels-photo-33327422.png?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "BI ravencrow",
    "id": "grade2_0046",
    "type": "verb"
  },
  {
    "word": "read",
    "phonetic": "/riːd/",
    "pos": "v.",
    "meaning": "读",
    "example": "I read books.",
    "unit": "Unit 6 My Day",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/1472856/pexels-photo-1472856.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Lisa from Pexels",
    "id": "grade2_0047",
    "type": "verb"
  },
  {
    "word": "go",
    "phonetic": "/ɡəʊ/",
    "pos": "v.",
    "meaning": "去",
    "example": "I go to school.",
    "unit": "Unit 6 My Day",
    "grade": "grade2",
    "level": "下册",
    "image": "https://images.pexels.com/photos/33758037/pexels-photo-33758037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Thuan Pham",
    "id": "grade2_0048",
    "type": "verb"
  },
  {
    "word": "hello",
    "phonetic": "None",
    "pos": "None",
    "meaning": "你好",
    "example": "None",
    "unit": "Unit 1 Hello",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/7186155/pexels-photo-7186155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ann H",
    "id": "grade2_0049",
    "type": "noun"
  },
  {
    "word": "hi",
    "phonetic": "None",
    "pos": "None",
    "meaning": "嗨",
    "example": "None",
    "unit": "Unit 1 Hello",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/10047276/pexels-photo-10047276.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Claudio Mota",
    "id": "grade2_0050",
    "type": "noun"
  },
  {
    "word": "good",
    "phonetic": "None",
    "pos": "None",
    "meaning": "好的",
    "example": "None",
    "unit": "Unit 1 Hello",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/10160718/pexels-photo-10160718.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Brett Jordan",
    "id": "grade2_0051",
    "type": "noun"
  },
  {
    "word": "morning",
    "phonetic": "None",
    "pos": "None",
    "meaning": "早上",
    "example": "None",
    "unit": "Unit 1 Hello",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/29561591/pexels-photo-29561591.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Lauma Augstkalne",
    "id": "grade2_0052",
    "type": "noun"
  },
  {
    "word": "afternoon",
    "phonetic": "None",
    "pos": "None",
    "meaning": "下午",
    "example": "None",
    "unit": "Unit 1 Hello",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30562548/pexels-photo-30562548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Brin Silver",
    "id": "grade2_0053",
    "type": "noun"
  },
  {
    "word": "evening",
    "phonetic": "None",
    "pos": "None",
    "meaning": "晚上",
    "example": "None",
    "unit": "Unit 1 Hello",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/12329965/pexels-photo-12329965.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Sydney  Haws",
    "id": "grade2_0054",
    "type": "noun"
  },
  {
    "word": "goodbye",
    "phonetic": "None",
    "pos": "None",
    "meaning": "再见",
    "example": "None",
    "unit": "Unit 1 Hello",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/3831887/pexels-photo-3831887.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "cottonbro studio",
    "id": "grade2_0055",
    "type": "noun"
  },
  {
    "word": "eye",
    "phonetic": "None",
    "pos": "None",
    "meaning": "眼睛",
    "example": "None",
    "unit": "Unit 2 My body",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/9930771/pexels-photo-9930771.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Maksim Goncharenok",
    "id": "grade2_0056",
    "type": "noun"
  },
  {
    "word": "ear",
    "phonetic": "None",
    "pos": "None",
    "meaning": "耳朵",
    "example": "None",
    "unit": "Unit 2 My body",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/8092973/pexels-photo-8092973.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "www.kaboompics.com",
    "id": "grade2_0057",
    "type": "noun"
  },
  {
    "word": "nose",
    "phonetic": "None",
    "pos": "None",
    "meaning": "鼻子",
    "example": "None",
    "unit": "Unit 2 My body",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/7479592/pexels-photo-7479592.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Angela Roma",
    "id": "grade2_0058",
    "type": "noun"
  },
  {
    "word": "mouth",
    "phonetic": "None",
    "pos": "None",
    "meaning": "嘴巴",
    "example": "None",
    "unit": "Unit 2 My body",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/3762453/pexels-photo-3762453.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Shiny Diamond",
    "id": "grade2_0059",
    "type": "noun"
  },
  {
    "word": "face",
    "phonetic": "None",
    "pos": "None",
    "meaning": "脸",
    "example": "None",
    "unit": "Unit 2 My body",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/18925606/pexels-photo-18925606.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Beyzanur K.",
    "id": "grade2_0060",
    "type": "noun"
  },
  {
    "word": "head",
    "phonetic": "None",
    "pos": "None",
    "meaning": "头",
    "example": "None",
    "unit": "Unit 2 My body",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/7479510/pexels-photo-7479510.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Angela Roma",
    "id": "grade2_0061",
    "type": "noun"
  },
  {
    "word": "hair",
    "phonetic": "None",
    "pos": "None",
    "meaning": "头发",
    "example": "None",
    "unit": "Unit 2 My body",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/7440132/pexels-photo-7440132.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "cottonbro studio",
    "id": "grade2_0062",
    "type": "noun"
  },
  {
    "word": "hand",
    "phonetic": "None",
    "pos": "None",
    "meaning": "手",
    "example": "None",
    "unit": "Unit 2 My body",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/20805375/pexels-photo-20805375.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Vera Emilie",
    "id": "grade2_0063",
    "type": "noun"
  },
  {
    "word": "room",
    "phonetic": "None",
    "pos": "None",
    "meaning": "房间",
    "example": "None",
    "unit": "Unit 3 My room",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/36852546/pexels-photo-36852546.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Misbaa eri",
    "id": "grade2_0064",
    "type": "noun"
  },
  {
    "word": "desk",
    "phonetic": "None",
    "pos": "None",
    "meaning": "书桌",
    "example": "None",
    "unit": "Unit 3 My room",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/8004023/pexels-photo-8004023.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Darina Belonogova",
    "id": "grade2_0065",
    "type": "noun"
  },
  {
    "word": "chair",
    "phonetic": "None",
    "pos": "None",
    "meaning": "椅子",
    "example": "None",
    "unit": "Unit 3 My room",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/7193706/pexels-photo-7193706.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "www.kaboompics.com",
    "id": "grade2_0066",
    "type": "noun"
  },
  {
    "word": "bed",
    "phonetic": "None",
    "pos": "None",
    "meaning": "床",
    "example": "None",
    "unit": "Unit 3 My room",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/32668690/pexels-photo-32668690.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Amina",
    "id": "grade2_0067",
    "type": "noun"
  },
  {
    "word": "book",
    "phonetic": "None",
    "pos": "None",
    "meaning": "书",
    "example": "None",
    "unit": "Unit 3 My room",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/415071/pexels-photo-415071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Pixabay",
    "id": "grade2_0068",
    "type": "noun"
  },
  {
    "word": "bag",
    "phonetic": "None",
    "pos": "None",
    "meaning": "书包",
    "example": "None",
    "unit": "Unit 3 My room",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/33235378/pexels-photo-33235378.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "oPorto",
    "id": "grade2_0069",
    "type": "noun"
  },
  {
    "word": "box",
    "phonetic": "None",
    "pos": "None",
    "meaning": "盒子",
    "example": "None",
    "unit": "Unit 3 My room",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/4554234/pexels-photo-4554234.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "cottonbro studio",
    "id": "grade2_0070",
    "type": "noun"
  },
  {
    "word": "boy",
    "phonetic": "None",
    "pos": "None",
    "meaning": "男孩",
    "example": "None",
    "unit": "Unit 4 My classmates",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/29586710/pexels-photo-29586710.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Prime Media Photography",
    "id": "grade2_0071",
    "type": "noun"
  },
  {
    "word": "girl",
    "phonetic": "None",
    "pos": "None",
    "meaning": "女孩",
    "example": "None",
    "unit": "Unit 4 My classmates",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/5037083/pexels-photo-5037083.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "KATRIN  BOLOVTSOVA",
    "id": "grade2_0072",
    "type": "noun"
  },
  {
    "word": "I",
    "phonetic": "None",
    "pos": "None",
    "meaning": "我",
    "example": "None",
    "unit": "Unit 4 My classmates",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/8473869/pexels-photo-8473869.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Cup of  Couple",
    "id": "grade2_0073",
    "type": "noun"
  },
  {
    "word": "you",
    "phonetic": "None",
    "pos": "None",
    "meaning": "你",
    "example": "None",
    "unit": "Unit 4 My classmates",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/32319653/pexels-photo-32319653.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ann H",
    "id": "grade2_0074",
    "type": "noun"
  },
  {
    "word": "he",
    "phonetic": "None",
    "pos": "None",
    "meaning": "他",
    "example": "None",
    "unit": "Unit 4 My classmates",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/8301098/pexels-photo-8301098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Hieu Phan",
    "id": "grade2_0075",
    "type": "noun"
  },
  {
    "word": "she",
    "phonetic": "None",
    "pos": "None",
    "meaning": "她",
    "example": "None",
    "unit": "Unit 4 My classmates",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/36485536/pexels-photo-36485536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Amar  Preciado",
    "id": "grade2_0076",
    "type": "noun"
  },
  {
    "word": "father",
    "phonetic": "None",
    "pos": "None",
    "meaning": "爸爸",
    "example": "None",
    "unit": "Unit 5 My family",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/4609047/pexels-photo-4609047.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Vlada Karpovich",
    "id": "grade2_0077",
    "type": "noun"
  },
  {
    "word": "mother",
    "phonetic": "None",
    "pos": "None",
    "meaning": "妈妈",
    "example": "None",
    "unit": "Unit 5 My family",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30225583/pexels-photo-30225583.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Asad Photo Maldives",
    "id": "grade2_0078",
    "type": "noun"
  },
  {
    "word": "brother",
    "phonetic": "None",
    "pos": "None",
    "meaning": "哥哥/弟弟",
    "example": "None",
    "unit": "Unit 5 My family",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/14195784/pexels-photo-14195784.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "rehman yousaf",
    "id": "grade2_0079",
    "type": "noun"
  },
  {
    "word": "sister",
    "phonetic": "None",
    "pos": "None",
    "meaning": "姐姐/妹妹",
    "example": "None",
    "unit": "Unit 5 My family",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/12789183/pexels-photo-12789183.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "VIKTOR KONDRATIUK",
    "id": "grade2_0080",
    "type": "noun"
  },
  {
    "word": "grandpa",
    "phonetic": "None",
    "pos": "None",
    "meaning": "爷爷/外公",
    "example": "None",
    "unit": "Unit 5 My family",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/7118191/pexels-photo-7118191.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "cottonbro studio",
    "id": "grade2_0081",
    "type": "noun"
  },
  {
    "word": "grandma",
    "phonetic": "None",
    "pos": "None",
    "meaning": "奶奶/外婆",
    "example": "None",
    "unit": "Unit 5 My family",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/9385076/pexels-photo-9385076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Анастасия Триббиани",
    "id": "grade2_0082",
    "type": "noun"
  },
  {
    "word": "tall",
    "phonetic": "None",
    "pos": "None",
    "meaning": "高的",
    "example": "None",
    "unit": "Unit 6 Me",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/10901185/pexels-photo-10901185.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Silke Schümann",
    "id": "grade2_0083",
    "type": "noun"
  },
  {
    "word": "short",
    "phonetic": "None",
    "pos": "None",
    "meaning": "矮的",
    "example": "None",
    "unit": "Unit 6 Me",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/29263907/pexels-photo-29263907.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Kalistro",
    "id": "grade2_0084",
    "type": "noun"
  },
  {
    "word": "fat",
    "phonetic": "None",
    "pos": "None",
    "meaning": "胖的",
    "example": "None",
    "unit": "Unit 6 Me",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/9927899/pexels-photo-9927899.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Towfiqu barbhuiya",
    "id": "grade2_0085",
    "type": "noun"
  },
  {
    "word": "thin",
    "phonetic": "None",
    "pos": "None",
    "meaning": "瘦的",
    "example": "None",
    "unit": "Unit 6 Me",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/7558834/pexels-photo-7558834.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Daniel Dan",
    "id": "grade2_0086",
    "type": "noun"
  },
  {
    "word": "big",
    "phonetic": "None",
    "pos": "None",
    "meaning": "大的",
    "example": "None",
    "unit": "Unit 6 Me",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/5662847/pexels-photo-5662847.png?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tima Miroshnichenko",
    "id": "grade2_0087",
    "type": "noun"
  },
  {
    "word": "small",
    "phonetic": "None",
    "pos": "None",
    "meaning": "小的",
    "example": "None",
    "unit": "Unit 6 Me",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/7563615/pexels-photo-7563615.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "RDNE Stock project",
    "id": "grade2_0088",
    "type": "noun"
  },
  {
    "word": "rice",
    "phonetic": "None",
    "pos": "None",
    "meaning": "米饭",
    "example": "None",
    "unit": "Unit 7 My favourite food",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/17563535/pexels-photo-17563535.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Jubair Bin Iqbal",
    "id": "grade2_0089",
    "type": "noun"
  },
  {
    "word": "egg",
    "phonetic": "None",
    "pos": "None",
    "meaning": "鸡蛋",
    "example": "None",
    "unit": "Unit 7 My favourite food",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/32149473/pexels-photo-32149473.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Christopher Welsch Leveroni",
    "id": "grade2_0090",
    "type": "noun"
  },
  {
    "word": "bread",
    "phonetic": "None",
    "pos": "None",
    "meaning": "面包",
    "example": "None",
    "unit": "Unit 7 My favourite food",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/32611701/pexels-photo-32611701.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nguyen Ngoc Tien",
    "id": "grade2_0091",
    "type": "noun"
  },
  {
    "word": "milk",
    "phonetic": "None",
    "pos": "None",
    "meaning": "牛奶",
    "example": "None",
    "unit": "Unit 7 My favourite food",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/4121867/pexels-photo-4121867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Olena Bohovyk",
    "id": "grade2_0092",
    "type": "noun"
  },
  {
    "word": "fish",
    "phonetic": "None",
    "pos": "None",
    "meaning": "鱼",
    "example": "None",
    "unit": "Unit 7 My favourite food",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/27322157/pexels-photo-27322157.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "gül aksoy",
    "id": "grade2_0093",
    "type": "noun"
  },
  {
    "word": "chicken",
    "phonetic": "None",
    "pos": "None",
    "meaning": "鸡肉",
    "example": "None",
    "unit": "Unit 7 My favourite food",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/29707952/pexels-photo-29707952.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Erik Karits",
    "id": "grade2_0094",
    "type": "noun"
  },
  {
    "word": "juice",
    "phonetic": "None",
    "pos": "None",
    "meaning": "果汁",
    "example": "None",
    "unit": "Unit 7 My favourite food",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/13211075/pexels-photo-13211075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Maria Tyutina",
    "id": "grade2_0095",
    "type": "noun"
  },
  {
    "word": "run",
    "phonetic": "None",
    "pos": "None",
    "meaning": "跑",
    "example": "None",
    "unit": "Unit 8 Playtime",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/11757388/pexels-photo-11757388.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mohammed Abubakr",
    "id": "grade2_0096",
    "type": "noun"
  },
  {
    "word": "jump",
    "phonetic": "None",
    "pos": "None",
    "meaning": "跳",
    "example": "None",
    "unit": "Unit 8 Playtime",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/5214079/pexels-photo-5214079.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "VV 97",
    "id": "grade2_0097",
    "type": "noun"
  },
  {
    "word": "skip",
    "phonetic": "None",
    "pos": "None",
    "meaning": "跳绳",
    "example": "None",
    "unit": "Unit 8 Playtime",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/35421540/pexels-photo-35421540.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "unavailable Photographer",
    "id": "grade2_0098",
    "type": "noun"
  },
  {
    "word": "swim",
    "phonetic": "None",
    "pos": "None",
    "meaning": "游泳",
    "example": "None",
    "unit": "Unit 8 Playtime",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/35156550/pexels-photo-35156550.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "david hou",
    "id": "grade2_0099",
    "type": "noun"
  },
  {
    "word": "ride",
    "phonetic": "None",
    "pos": "None",
    "meaning": "骑",
    "example": "None",
    "unit": "Unit 8 Playtime",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/11184869/pexels-photo-11184869.png?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Matheus  Lopes",
    "id": "grade2_0100",
    "type": "noun"
  },
  {
    "word": "fly",
    "phonetic": "None",
    "pos": "None",
    "meaning": "飞",
    "example": "None",
    "unit": "Unit 8 Playtime",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30171437/pexels-photo-30171437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "KRH Amir hamja official",
    "id": "grade2_0101",
    "type": "noun"
  },
  {
    "word": "red",
    "phonetic": "None",
    "pos": "None",
    "meaning": "红色",
    "example": "None",
    "unit": "Unit 1 Colours",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/16241347/pexels-photo-16241347.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tom Fisk",
    "id": "grade2_0102",
    "type": "noun"
  },
  {
    "word": "yellow",
    "phonetic": "None",
    "pos": "None",
    "meaning": "黄色",
    "example": "None",
    "unit": "Unit 1 Colours",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/36165185/pexels-photo-36165185.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Daniel  Wells",
    "id": "grade2_0103",
    "type": "noun"
  },
  {
    "word": "blue",
    "phonetic": "None",
    "pos": "None",
    "meaning": "蓝色",
    "example": "None",
    "unit": "Unit 1 Colours",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/281260/pexels-photo-281260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Francesco Ungaro",
    "id": "grade2_0104",
    "type": "noun"
  },
  {
    "word": "green",
    "phonetic": "None",
    "pos": "None",
    "meaning": "绿色",
    "example": "None",
    "unit": "Unit 1 Colours",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/34328418/pexels-photo-34328418.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Niraj Yadav",
    "id": "grade2_0105",
    "type": "noun"
  },
  {
    "word": "black",
    "phonetic": "None",
    "pos": "None",
    "meaning": "黑色",
    "example": "None",
    "unit": "Unit 1 Colours",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/4862953/pexels-photo-4862953.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "www.kaboompics.com",
    "id": "grade2_0106",
    "type": "noun"
  },
  {
    "word": "white",
    "phonetic": "None",
    "pos": "None",
    "meaning": "白色",
    "example": "None",
    "unit": "Unit 1 Colours",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/1597623/pexels-photo-1597623.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ethan Wu",
    "id": "grade2_0107",
    "type": "noun"
  },
  {
    "word": "orange",
    "phonetic": "None",
    "pos": "None",
    "meaning": "橙色",
    "example": "None",
    "unit": "Unit 1 Colours",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/820903/pexels-photo-820903.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Jessica Lewis 🦋 thepaintedsquare",
    "id": "grade2_0108",
    "type": "noun"
  },
  {
    "word": "brown",
    "phonetic": "None",
    "pos": "None",
    "meaning": "棕色",
    "example": "None",
    "unit": "Unit 1 Colours",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/5912675/pexels-photo-5912675.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tima Miroshnichenko",
    "id": "grade2_0109",
    "type": "noun"
  },
  {
    "word": "ball",
    "phonetic": "None",
    "pos": "None",
    "meaning": "球",
    "example": "None",
    "unit": "Unit 2 Toys",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/11415807/pexels-photo-11415807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tamhasip Khan",
    "id": "grade2_0110",
    "type": "noun"
  },
  {
    "word": "doll",
    "phonetic": "None",
    "pos": "None",
    "meaning": "娃娃",
    "example": "None",
    "unit": "Unit 2 Toys",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30312326/pexels-photo-30312326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "İsra Nilgün Özkan",
    "id": "grade2_0111",
    "type": "noun"
  },
  {
    "word": "kite",
    "phonetic": "None",
    "pos": "None",
    "meaning": "风筝",
    "example": "None",
    "unit": "Unit 2 Toys",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/35098545/pexels-photo-35098545.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ty Nguyễn",
    "id": "grade2_0112",
    "type": "noun"
  },
  {
    "word": "bike",
    "phonetic": "None",
    "pos": "None",
    "meaning": "自行车",
    "example": "None",
    "unit": "Unit 2 Toys",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/31492382/pexels-photo-31492382.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ravi Roshan",
    "id": "grade2_0113",
    "type": "noun"
  },
  {
    "word": "robot",
    "phonetic": "None",
    "pos": "None",
    "meaning": "机器人",
    "example": "None",
    "unit": "Unit 2 Toys",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/8566521/pexels-photo-8566521.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Kindel Media",
    "id": "grade2_0114",
    "type": "noun"
  },
  {
    "word": "car",
    "phonetic": "None",
    "pos": "None",
    "meaning": "小汽车",
    "example": "None",
    "unit": "Unit 2 Toys",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/1972736/pexels-photo-1972736.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tom Verdoot",
    "id": "grade2_0115",
    "type": "noun"
  },
  {
    "word": "sunny",
    "phonetic": "None",
    "pos": "None",
    "meaning": "晴朗的",
    "example": "None",
    "unit": "Unit 3 Weather",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/31608593/pexels-photo-31608593.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mohamed B.",
    "id": "grade2_0116",
    "type": "noun"
  },
  {
    "word": "rainy",
    "phonetic": "None",
    "pos": "None",
    "meaning": "下雨的",
    "example": "None",
    "unit": "Unit 3 Weather",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/4396956/pexels-photo-4396956.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nothing Ahead",
    "id": "grade2_0117",
    "type": "noun"
  },
  {
    "word": "windy",
    "phonetic": "None",
    "pos": "None",
    "meaning": "有风的",
    "example": "None",
    "unit": "Unit 3 Weather",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/1030320/pexels-photo-1030320.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Suparerg Suksai",
    "id": "grade2_0118",
    "type": "noun"
  },
  {
    "word": "cloudy",
    "phonetic": "None",
    "pos": "None",
    "meaning": "多云的",
    "example": "None",
    "unit": "Unit 3 Weather",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/27671469/pexels-photo-27671469.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "AhmadReza Pishnamazi",
    "id": "grade2_0119",
    "type": "noun"
  },
  {
    "word": "hot",
    "phonetic": "None",
    "pos": "None",
    "meaning": "热的",
    "example": "None",
    "unit": "Unit 3 Weather",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/3309748/pexels-photo-3309748.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Jill Wellington",
    "id": "grade2_0120",
    "type": "noun"
  },
  {
    "word": "cold",
    "phonetic": "None",
    "pos": "None",
    "meaning": "冷的",
    "example": "None",
    "unit": "Unit 3 Weather",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/906020/pexels-photo-906020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Noelle Otto",
    "id": "grade2_0121",
    "type": "noun"
  },
  {
    "word": "warm",
    "phonetic": "None",
    "pos": "None",
    "meaning": "温暖的",
    "example": "None",
    "unit": "Unit 3 Weather",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/9138927/pexels-photo-9138927.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Alejandro Galván",
    "id": "grade2_0122",
    "type": "noun"
  },
  {
    "word": "spring",
    "phonetic": "None",
    "pos": "None",
    "meaning": "春天",
    "example": "None",
    "unit": "Unit 4 Seasons",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/16050153/pexels-photo-16050153.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Marcelo Verfe",
    "id": "grade2_0123",
    "type": "noun"
  },
  {
    "word": "summer",
    "phonetic": "None",
    "pos": "None",
    "meaning": "夏天",
    "example": "None",
    "unit": "Unit 4 Seasons",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/33643604/pexels-photo-33643604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Jan van der Wolf",
    "id": "grade2_0124",
    "type": "noun"
  },
  {
    "word": "autumn",
    "phonetic": "None",
    "pos": "None",
    "meaning": "秋天",
    "example": "None",
    "unit": "Unit 4 Seasons",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/35016563/pexels-photo-35016563.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "İbrahim Erkan Bayram | iebarts",
    "id": "grade2_0125",
    "type": "noun"
  },
  {
    "word": "winter",
    "phonetic": "None",
    "pos": "None",
    "meaning": "冬天",
    "example": "None",
    "unit": "Unit 4 Seasons",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30757598/pexels-photo-30757598.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mustafa Mašetić",
    "id": "grade2_0126",
    "type": "noun"
  },
  {
    "word": "coat",
    "phonetic": "None",
    "pos": "None",
    "meaning": "外套",
    "example": "None",
    "unit": "Unit 5 Clothes",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/9968481/pexels-photo-9968481.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Vlada Karpovich",
    "id": "grade2_0127",
    "type": "noun"
  },
  {
    "word": "dress",
    "phonetic": "None",
    "pos": "None",
    "meaning": "连衣裙",
    "example": "None",
    "unit": "Unit 5 Clothes",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/17471951/pexels-photo-17471951.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "High  Rollick studio",
    "id": "grade2_0128",
    "type": "noun"
  },
  {
    "word": "skirt",
    "phonetic": "None",
    "pos": "None",
    "meaning": "短裙",
    "example": "None",
    "unit": "Unit 5 Clothes",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/34966857/pexels-photo-34966857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Rue Mareq",
    "id": "grade2_0129",
    "type": "noun"
  },
  {
    "word": "shirt",
    "phonetic": "None",
    "pos": "None",
    "meaning": "衬衫",
    "example": "None",
    "unit": "Unit 5 Clothes",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/31842962/pexels-photo-31842962.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nimit N",
    "id": "grade2_0130",
    "type": "noun"
  },
  {
    "word": "shoe",
    "phonetic": "None",
    "pos": "None",
    "meaning": "鞋子",
    "example": "None",
    "unit": "Unit 5 Clothes",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/10352336/pexels-photo-10352336.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nikita Nikitin",
    "id": "grade2_0131",
    "type": "noun"
  },
  {
    "word": "water",
    "phonetic": "None",
    "pos": "None",
    "meaning": "水",
    "example": "None",
    "unit": "Unit 6 Drinks",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30296727/pexels-photo-30296727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ramon Hernandez",
    "id": "grade2_0132",
    "type": "noun"
  },
  {
    "word": "tea",
    "phonetic": "None",
    "pos": "None",
    "meaning": "茶",
    "example": "None",
    "unit": "Unit 6 Drinks",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/29481927/pexels-photo-29481927.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "ufuk iseloglu",
    "id": "grade2_0133",
    "type": "noun"
  },
  {
    "word": "milk",
    "phonetic": "None",
    "pos": "None",
    "meaning": "牛奶",
    "example": "None",
    "unit": "Unit 6 Drinks",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/4121867/pexels-photo-4121867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Olena Bohovyk",
    "id": "grade2_0134",
    "type": "noun"
  },
  {
    "word": "juice",
    "phonetic": "None",
    "pos": "None",
    "meaning": "果汁",
    "example": "None",
    "unit": "Unit 6 Drinks",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/13211075/pexels-photo-13211075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Maria Tyutina",
    "id": "grade2_0135",
    "type": "noun"
  },
  {
    "word": "cola",
    "phonetic": "None",
    "pos": "None",
    "meaning": "可乐",
    "example": "None",
    "unit": "Unit 6 Drinks",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/4113670/pexels-photo-4113670.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "alleksana",
    "id": "grade2_0136",
    "type": "noun"
  },
  {
    "word": "cat",
    "phonetic": "None",
    "pos": "None",
    "meaning": "猫",
    "example": "None",
    "unit": "Unit 7 Animals",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30002394/pexels-photo-30002394.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Helena Jankovičová Kováčová",
    "id": "grade2_0137",
    "type": "noun"
  },
  {
    "word": "dog",
    "phonetic": "None",
    "pos": "None",
    "meaning": "狗",
    "example": "None",
    "unit": "Unit 7 Animals",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/27107874/pexels-photo-27107874.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Chirag Captures",
    "id": "grade2_0138",
    "type": "noun"
  },
  {
    "word": "bird",
    "phonetic": "None",
    "pos": "None",
    "meaning": "小鸟",
    "example": "None",
    "unit": "Unit 7 Animals",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/29275539/pexels-photo-29275539.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Enrique Hidalgo",
    "id": "grade2_0139",
    "type": "noun"
  },
  {
    "word": "panda",
    "phonetic": "None",
    "pos": "None",
    "meaning": "熊猫",
    "example": "None",
    "unit": "Unit 7 Animals",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30415353/pexels-photo-30415353.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Snow Chang",
    "id": "grade2_0140",
    "type": "noun"
  },
  {
    "word": "tiger",
    "phonetic": "None",
    "pos": "None",
    "meaning": "老虎",
    "example": "None",
    "unit": "Unit 7 Animals",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/18150604/pexels-photo-18150604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Thang Cao",
    "id": "grade2_0141",
    "type": "noun"
  },
  {
    "word": "monkey",
    "phonetic": "None",
    "pos": "None",
    "meaning": "猴子",
    "example": "None",
    "unit": "Unit 7 Animals",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/32860812/pexels-photo-32860812.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Hobi Photography",
    "id": "grade2_0142",
    "type": "noun"
  },
  {
    "word": "morning",
    "phonetic": "None",
    "pos": "None",
    "meaning": "早上",
    "example": "None",
    "unit": "Unit 8 Time",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/29561591/pexels-photo-29561591.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Lauma Augstkalne",
    "id": "grade2_0143",
    "type": "noun"
  },
  {
    "word": "afternoon",
    "phonetic": "None",
    "pos": "None",
    "meaning": "下午",
    "example": "None",
    "unit": "Unit 8 Time",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/30562548/pexels-photo-30562548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Brin Silver",
    "id": "grade2_0144",
    "type": "noun"
  },
  {
    "word": "evening",
    "phonetic": "None",
    "pos": "None",
    "meaning": "傍晚",
    "example": "None",
    "unit": "Unit 8 Time",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/12329965/pexels-photo-12329965.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Sydney  Haws",
    "id": "grade2_0145",
    "type": "noun"
  },
  {
    "word": "night",
    "phonetic": "None",
    "pos": "None",
    "meaning": "夜晚",
    "example": "None",
    "unit": "Unit 8 Time",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/8206412/pexels-photo-8206412.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Zehra Nur  Peltek",
    "id": "grade2_0146",
    "type": "noun"
  },
  {
    "word": "time",
    "phonetic": "None",
    "pos": "None",
    "meaning": "时间",
    "example": "None",
    "unit": "Unit 8 Time",
    "grade": "grade2",
    "level": "上册",
    "image": "https://images.pexels.com/photos/48770/business-time-clock-clocks-48770.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Pixabay",
    "id": "grade2_0147",
    "type": "noun"
  }
];

export default async function handler(request, context) {
  // 处理 CORS
  const headers = new Headers();
  headers.set('Access-Control-Allow-Origin', '*');
  headers.set('Access-Control-Allow-Methods', 'GET, OPTIONS');
  headers.set('Access-Control-Allow-Headers', 'Content-Type');
  
  if (request.method === 'OPTIONS') {
    return new Response(null, { headers });
  }
  
  // 返回词库数据
  const response = new Response(JSON.stringify({
    words: WORD_DATA,
    total: WORD_DATA.length,
    updatedAt: new Date().toISOString()
  }), {
    headers: {
      ...Object.fromEntries(headers),
      'Content-Type': 'application/json'
    }
  });
  
  return response;
}
